2018-05-15 15:09:03,187 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-15 16:00:46,374 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-15 16:17:52,483 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:18:10,011 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:24:52,274 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:24:56,976 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:25:23,980 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:25:29,113 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:25:32,902 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:25:57,468 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:26:05,056 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:26:49,175 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:29:23,939 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:30:49,051 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:31:17,822 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 09:45:13,234 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 14:45:17,534 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 14:55:41,586 ERROR: Exception on /search [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 67, in search
    form.bp.data, form.in_scope.data)
  File "D:\flask\stageopdracht\app\my_scribbles.py", line 337, in search_db
    modules1 = Module.query.filter(and_(Module.addon.like('%' + form_module_data.split(' ') + '%'),
TypeError: must be str, not list
2018-05-16 15:17:37,833 ERROR: Exception on /search [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 67, in search
    form.bp.data, form.in_scope.data)
  File "D:\flask\stageopdracht\app\my_scribbles.py", line 337, in search_db
    modules1 = Module.query.filter(and_(Module.addon.like('%' + form_module_data.split(' ') + '%'),
TypeError: must be str, not list
2018-05-16 15:20:03,940 ERROR: Exception on /search [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 67, in search
    form.bp.data, form.in_scope.data)
  File "D:\flask\stageopdracht\app\my_scribbles.py", line 337, in search_db
    modules1 = Module.query.filter(and_(Module.addon.like('%' + form_module_data.split(' ') + '%'),
TypeError: must be str, not list
2018-05-16 15:21:01,595 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:16:39,040 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:16:58,587 ERROR: Exception on /search [GET] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 62, in search
    form = SearchForm()
NameError: name 'SearchForm' is not defined
2018-05-16 16:18:49,787 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:18:51,569 ERROR: Exception on /search [GET] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 62, in search
    form = SearchForm()
NameError: name 'SearchForm' is not defined
2018-05-16 16:19:20,302 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:19:20,540 ERROR: Exception on /search [GET] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 62, in search
    form = SearchForm()
NameError: name 'SearchForm' is not defined
2018-05-16 16:21:04,213 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:22:23,621 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:22:51,596 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:23:17,488 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:23:53,804 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:28:08,854 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:28:47,103 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:29:18,354 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:30:04,676 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:30:24,213 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
